const words = [
'Jean-Jacques Goldman',
'Omar Sy',
'Dany Boon',
'Kylian Mbappé',
'Thomas Pesquet',
'Zinédine Zidane',
'Michel Cymes',
'Jean Reno',
'Jean-Paul Belmondo',
'Soprano',
'Jean-Pierre Pernaut',
'Teddy Riner',
'Michel Sardou',
'Jean Dujardin',
'Antoine Griezmann',
'Sophie Marceau',
'Jean-Luc Reichmann',
'Laurent Gerra',
'Renaud',
'Fabrice Luchini',
'Francis Cabrel',
'Jamel Debbouze',
'Florence Foresti',
'Gad Elmaleh',
'Gérard Jugnot',
'Mimie Mathy',
'Patrick Bruel',
'Stéphane Bern',
'N\'Golo Kanté',
'Florent Pagny',
'Élise Lucet',
'Louane',
'Nagui',
'Alain Souchon',
'Didier Deschamps',
'Franck Dubosc',
'Valérie Lemercier',
'Muriel Robin',
'Mylène Farmer',
'Josiane Balasko',
'Ingrid Chauvin',
'Karine Le Marchand',
'Nicolas Hulot',
'Kad Merad',
'Zazie',
'Nolwenn Leroy',
'Line Renaud',
'Hugo Lloris',
'Nicolas Canteloup',
'Paul Pogba',
]

export {words};